### ISSUE TITLE
install and import

### ISSUE THREAD

**Issue by yoakiyama** [LeaVerou/svelte-scrolly#1]
Hi Lea. I am trying to use the package in a svelte file, but I'm running into some issues. As shown in Lab 9, I ran `npm install svelte-scrolly`, and in my svelte file, I have `import Scrolly from "svelte-scrolly";`

I'm now seeing `Could not find a declaration file for module 'svelte-scrolly'. '/Users/<user>/Desktop/zoning-dashboard-fp/node_modules/svelte-scrolly/Scrolly.svelte' implicitly has an 'any' type.` 

Do you know how I may solve this issue? Thanks!

**Comment by LeaVerou** [comment]
Sorry, I didn’t see this as it was the weekend. I see you closed it. Was it not an issue with this component?
